spring:
  mail:
    host: smtp.163.com
    username: yourEmail@163.com
    password: yourEmailPwd
    default-encoding: UTF-8
    #mvc:
    #throw-exception-if-no-handler-found: true
    #static-path-pattern: /templates/**
  thymeleaf:
    encoding: utf-8
    mode: HTML5  #LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  application:
    name: email_demo
server:
  port: 7878
logging:
  config: classpath:logback-spring.xml



